#!/usr/bin/python


'''
Written by Dominic Bolding for myhydropi.com 2016

Feel free to use and modify this code for you own use in any way.

This program is designed to turn 4 relays on and off every 5 seconds

While the code looks counter intuitive by setting the GPIO pin to “true”
to turn off the relay this is actually correct due to the fact that the
relay that I am using is configured as active low.

If you have a relay that is active high or are using LED's then reverse the
True and False settings'
''' 

import RPi.GPIO as GPIO  # Import GPIO Module
from time import sleep  # Import sleep Module for timing

GPIO.setmode(GPIO.BCM)  # Configures how we are describing our pin numbering
GPIO.setwarnings(False)  # Disable Warnings

#Set our GPIO pins to outputs and set them to off

GPIO.setup(22, GPIO.OUT)
GPIO.output(22, True)
GPIO.setup(23, GPIO.OUT)
GPIO.output(23, True)
GPIO.setup(24, GPIO.OUT)
GPIO.output(24, True)
GPIO.setup(25, GPIO.OUT)
GPIO.output(25, True)


while (True):

# Turn all relays ON
    GPIO.output(22, False)
    GPIO.output(23, False)
    GPIO.output(24, False)
    GPIO.output(25, False)
# Sleep for 5 seconds
    sleep(5)
# Turn all relays OFF
    GPIO.output(22, True)
    GPIO.output(23, True)
    GPIO.output(24, True)
    GPIO.output(25, True)
# Sleep for 5 seconds
    sleep(5)
