#!/usr/bin/env python

##############################################################################
#
# Written by Dominic Bolding for the Raspberry Pi - 2017
#
# Website: myhydropi.com
# Contact: admin@myhydropi.com
#
# Feel free to use and modify this code for you own use in any way.
#
# This program is designed to provide the following features and should be run
# initially from the command line so that a couple of configuration errors can
# be tested for and warnings provided on screen:
#
# 1. Read Multiple Sensors - DS18B20 1-wire type Temperature sensors, Atlas
# Scientific Temperature, pH, Oxidation Reduction Potential (ORP) and
# Electrical Conductivity sensors and save the results to a MySQL database at
# a set interval with a set level of accuracy. Multiple sensors of the same
# type can also be used by configuring the "sensors" variable with the correct
# sensor type. A reference temperature reading will be set by one of the
# temperature sensors if any are connected, if not a value of 25C will be
# applied. This is necessary to ensure accurate readings from the other
# sensors as the liquid being tested changes temperature.
# The electrical conductivity reading is also converted to parts per million.
# There is also a customizible "pause" setting included to stop readings while
# chemicals are being added, this prevents spikes in the readings for more
# accurate results.
#
# 2. The program will also create the initial database and tables if they do
# not already exist in MySQL.
#
##############################################################################

import os
import sys
import time
import MySQLdb
import MySQLdb.cursors
from collections import OrderedDict
from pylibftdi.device import Device
from pylibftdi.driver import FtdiError


# Uncomment sleep if running program at startup with crontab

#sleep(10)

# Load Raspberry Pi Drivers for 1-Wire Temperature Sensor

os.system('modprobe w1-gpio')
os.system('modprobe w1-therm')

# Define Atlas Scientific Device Class


class AtlasDevice(Device):

    def read_line(self):
        """
        Read the response from the Atlas Sensor
        :return:
        """
        line_buffer = []
        try:
            start_time = time.time()
            while True:

                # read bytes until Carriage Return is received.
                next_char = self.read(1)    # read one byte
                if next_char == "\r":  # response of sensor always ends with CR.
                    break
                line_buffer.append(next_char)

                if time.time() - start_time > 1.0:  # timeout
                    line_buffer = ''
                    break
            return ''.join(line_buffer)

        except FtdiError:
            return ''

    def send_cmd(self, cmd):
        """
        Send command to the Atlas Sensor.
        Before sending, add Carriage Return at the end of the command.
        :param cmd:
        :return:
        """
        buf = cmd + "\r"     	# add carriage return
        try:
            self.write(buf)
            return True
        except FtdiError:
            return False


# Check that only one Primary Temperature sensor is defined


def check_for_only_one_reference_temperature():

    ref_check = 0

    for key, value in sensors.items():
        if (value["is_connected"]) is True:
            if value["sensor_type"] == "1_wire_temp":
                if value["is_ref"] is True:
                    ref_check += 1
            if value["sensor_type"] == "atlas_temp":
                if value["is_ref"] is True:
                    ref_check += 1
    if ref_check > 1:
        os.system('clear')
        print ("\n\n                     !!!! WARNING !!!!\n\n"
        "You can only have one Primary Temperature sensor, Please set the\n"
        "Temperature sensor that is in the liquid you are testing to True\n"
        "and the other to False\n\n                     !!!! WARNING !!!!\n\n")
        sys.exit()  # Stop program
    return

# Create required database in the MySQL if it doesn't' already exist


def create_database():

    conn = MySQLdb.connect(servername, username, password)
    curs = conn.cursor()
    curs.execute("SET sql_notes = 0; ")  # Hide Warnings

    curs.execute("CREATE DATABASE IF NOT EXISTS {}".format(dbname))

    curs.execute("SET sql_notes = 1; ")  # Show Warnings
    conn.commit()
    conn.close()
    return


def open_database_connection():

    conn = MySQLdb.connect(servername, username, password, dbname)
    curs = conn.cursor()
    curs.execute("SET sql_notes = 0; ")  # Hide Warnings

    return conn, curs


def close_database_connection(conn, curs):

    curs.execute("SET sql_notes = 1; ")
    conn.commit()
    conn.close()


def create_sensors_table():

    conn, curs = open_database_connection()

    curs.execute("CREATE TABLE IF NOT EXISTS sensors (timestamp DATETIME);")

    for key, value in sensors.items():
        if value["is_connected"] is True:
            try:
                curs.execute("ALTER TABLE sensors ADD {} DECIMAL(10,2);"
                .format(value["name"]))
            except:
                pass

    close_database_connection(conn, curs)

    return


def remove_unused_sensors():

    conn, curs = open_database_connection()

    for key, value in sensors.items():
        if value["is_connected"] is False:
            try:
                curs.execute("ALTER TABLE sensors DROP {};"
                            .format(value["name"]))
            except:
                pass

    close_database_connection(conn, curs)

    return


def read_1_wire_temp_raw(temp_num):

        f = open(sensors[temp_num]["ds18b20_file"], 'r')
        lines = f.readlines()
        f.close()

        return lines

# Process the Temp Sensor file for errors and convert to degrees C


def read_1_wire_temp(temp_num):

    lines = read_1_wire_temp_raw(temp_num)

    while lines[0].strip()[-3:] != 'YES':
        time.sleep(0.2)
        lines = read_1_wire_temp_raw()
    equals_pos = lines[1].find('t=')

    if equals_pos != -1:
        temp_string = lines[1][equals_pos + 2:]
        # Use line below for Celsius
        temp_curr = float(temp_string) / 1000.0
        #Uncomment line below for Fahrenheit
        #temp_curr = ((float(temp_string) / 1000.0) * (9.0 / 5.0)) + 32

        return temp_curr

# read and log each sensor if it is set to True in the sensors list


def log_sensor_readings(all_curr_readings):

    # Create a timestamp and store all readings on the MySQL database

    conn, curs = open_database_connection()

    curs.execute("INSERT INTO sensors (timestamp) VALUES(now());")
    curs.execute("SELECT MAX(timestamp) FROM sensors")
    last_timestamp = curs.fetchone()
    last_timestamp = last_timestamp[0].strftime('%Y-%m-%d %H:%M:%S')

    for readings in all_curr_readings:
        try:
            curs.execute(("UPDATE sensors SET {} = {} WHERE timestamp = '{}'")
                        .format(readings[0], readings[1], last_timestamp))
        except:
            pass

    close_database_connection(conn, curs)

    return


def read_sensors():

    all_curr_readings = []
    ref_temp = 25

    # Get the readings from any 1-Wire temperature sensors

    for key, value in sensors.items():
        if value["is_connected"] is True:
            if value["sensor_type"] == "1_wire_temp":
                sensor_reading = (round(float(read_1_wire_temp(key)),
                                 value["accuracy"]))
                all_curr_readings.append([value["name"], sensor_reading])
                if value["is_ref"] is True:
                    ref_temp = sensor_reading

    # Get the readings from any Atlas Scientific temperature sensors

            elif value["sensor_type"] == "atlas_scientific_temp":
                dev = AtlasDevice(value["serial_number"])
                dev.send_cmd("R")
                sensor_reading = round(float(dev.read_line()),
                                value["accuracy"])
                all_curr_readings.append([value["name"], sensor_reading])
                if value["is_ref"] is True:
                    ref_temp = sensor_reading

            else:
                dev = AtlasDevice(value["serial_number"])
                # Set reference temperature value on the sensor
                dev.send_cmd("T," + str(ref_temp))

    # Get the readings from any Atlas Scientific Elec Conductivity sensors

                if value["sensor_type"] == "atlas_scientific_ec":
                    dev = AtlasDevice(value["serial_number"])
                    dev.send_cmd("R")
                    sensor_reading = (round(((float(dev.read_line())) *
                                  value["ppm_multiplier"]), value["accuracy"]))

    # Get the readings from any other Atlas Scientific sensors

                else:
                    dev = AtlasDevice(value["serial_number"])
                    dev.send_cmd("R")
                    sensor_reading = round(float(dev.read_line()),
                                    value["accuracy"])
                    all_curr_readings.append([value["name"], sensor_reading])

    log_sensor_readings(all_curr_readings)

    return


# Configuration Settings

# Define the sensor names, what sensors are connected, the sensor type, the
# atlas scientific sensor Serial Number and define a primary temperature sensor.
# In the case shown below that would be either "temp_1" or "atlas_sensor_1".
# This is the sensor that is in the liquid that is being sampled and is used
# as a reference by the other sensors. If there are no temperature sensors
# connected a default value of 25C will be applied.
#
# Note: The temperature sensors cannot both be set to "is_ref: True", also
# "temp_1" must always be a DS18B20 type sensor and "atlas_sensor_1" must
# always be an Atlas Scientific type temperature sensor so that the reference
# temperature is always set before the other Atlas Scientific sensors are read.

sensors = OrderedDict([("temp_1", {  # DS18B20 Temperature Sensor
                            "sensor_type": "1_wire_temp",
                            "name": "ds18b20_temp",
                            "is_connected": True,
                            "is_ref": False,
                            "ds18b20_file":
                            "/sys/bus/w1/devices/28-01157127dfff/w1_slave",
                            "accuracy": 1}),

                       ("atlas_sensor_1", {  # Atlas Scientific Temp Sensor
                            "sensor_type": "atlas_scientific_temp",
                            "name": "atlas_temp",
                            "is_connected": True,
                            "is_ref": True,
                            "serial_number": 1,  # Enter Serial Number
                            "accuracy": 1}),

                       ("atlas_sensor_2", {  # pH/ORP Atlas Scientific Sensor
                            "sensor_type": "atlas_scientific",
                            "name": "ph",
                            "is_connected": True,
                            "is_ref": False,
                            "serial_number": 1,  # Enter Serial Number
                            "accuracy": 2}),

                       ("atlas_sensor_3", {  # pH/ORP Atlas Scientific Sensor
                            "sensor_type": "atlas_scientific",
                            "name": "orp",
                            "is_connected": True,
                            "is_ref": False,
                            "serial_number": 1,  # Enter Serial Number
                            "accuracy": 0}),

                       ("atlas_sensor_4", {  # Atlas Scientific EC Sensor
                            "sensor_type": "atlas_scientific_ec",
                            "name": "ec",
                            "is_connected": True,
                            "is_ref": False,
                            "serial_number": 1,  # Enter Serial Number
                            "accuracy": 0,
                            "ppm_multiplier": 0.67})])  # Convert EC to PPM

# Define MySQL database login settings

servername = "localhost"
username = "YourMysqlUsername"
password = "YourMysqlPassword"
dbname = "YourMysqlDatabaseName"

loops = 0  # Set starting loops count for timing relay and sensor readings


#################
#               #
# Main Program  #
#               #
#################


# Sanity Checks

check_for_only_one_reference_temperature()

# Build/Remove MySQL Database Entries

create_database()
create_sensors_table()
remove_unused_sensors()

while True:  # Repeat the code indefinitely

    if loops == 300:
        loops = 0

        read_sensors()

    loops += 1
    time.sleep(1)
